/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLElement {
    componentOnReady?: () => Promise<this | null>;
  }

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}

import {
  ImgZoomSettings,
} from './components/img-zoom/img-zoom';

declare global {

  namespace StencilComponents {
    interface ImgZoom {
      'alt': string;
      'settings': ImgZoomSettings;
      'src': string;
    }
  }

  interface HTMLImgZoomElement extends StencilComponents.ImgZoom, HTMLStencilElement {}

  var HTMLImgZoomElement: {
    prototype: HTMLImgZoomElement;
    new (): HTMLImgZoomElement;
  };
  interface HTMLElementTagNameMap {
    'img-zoom': HTMLImgZoomElement;
  }
  interface ElementTagNameMap {
    'img-zoom': HTMLImgZoomElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'img-zoom': JSXElements.ImgZoomAttributes;
    }
  }
  namespace JSXElements {
    export interface ImgZoomAttributes extends HTMLAttributes {
      'alt'?: string;
      'settings'?: ImgZoomSettings;
      'src'?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;